// AUTO-GENERATED BY generate_x86.py - DO NOT EDIT

#[derive(Clone, Copy)]
pub enum Mnemonic {

    Aaa,
    Aad,
    Aam,
    Aas,
    Adc,
    Add,
    Addpd,
    Addps,
    Addsd,
    Addss,
    Addsubpd,
    Addsubps,
    Adx,
    Amx,
    And,
    Andnpd,
    Andnps,
    Andpd,
    Andps,
    Arpl,
    Blendpd,
    Blendps,
    Blendvpd,
    Blendvps,
    Bound,
    Bsf,
    Bsr,
    Bswap,
    Bt,
    Btc,
    Btr,
    Bts,
    Call,
    Callf,
    Cbw,
    Cdq,
    Cdqe,
    Clc,
    Cld,
    Clflush,
    Cli,
    Clts,
    Cmc,
    Cmova,
    Cmovae,
    Cmovb,
    Cmovbe,
    Cmovc,
    Cmove,
    Cmovg,
    Cmovge,
    Cmovl,
    Cmovle,
    Cmovna,
    Cmovnae,
    Cmovnb,
    Cmovnbe,
    Cmovnc,
    Cmovne,
    Cmovng,
    Cmovnge,
    Cmovnl,
    Cmovnle,
    Cmovno,
    Cmovnp,
    Cmovns,
    Cmovnz,
    Cmovo,
    Cmovp,
    Cmovpe,
    Cmovpo,
    Cmovs,
    Cmovz,
    Cmp,
    Cmppd,
    Cmpps,
    Cmps,
    Cmpsb,
    Cmpsd,
    Cmpsq,
    Cmpss,
    Cmpsw,
    Cmpxchg,
    Cmpxchg16b,
    Cmpxchg8b,
    Comisd,
    Comiss,
    Cpuid,
    Cqo,
    Crc32,
    Cvtdq2pd,
    Cvtdq2ps,
    Cvtpd2dq,
    Cvtpd2pi,
    Cvtpd2ps,
    Cvtpi2pd,
    Cvtpi2ps,
    Cvtps2dq,
    Cvtps2pd,
    Cvtps2pi,
    Cvtsd2si,
    Cvtsd2ss,
    Cvtsi2sd,
    Cvtsi2ss,
    Cvtss2sd,
    Cvtss2si,
    Cvttpd2dq,
    Cvttpd2pi,
    Cvttps2dq,
    Cvttps2pi,
    Cvttsd2si,
    Cvttss2si,
    Cwd,
    Cwde,
    Daa,
    Das,
    Dec,
    Div,
    Divpd,
    Divps,
    Divsd,
    Divss,
    Dppd,
    Dpps,
    Emms,
    Enter,
    Extractps,
    F2xm1,
    Fabs,
    Fadd,
    Faddp,
    Fbld,
    Fbstp,
    Fchs,
    Fclex,
    Fcmovb,
    Fcmovbe,
    Fcmove,
    Fcmovnb,
    Fcmovnbe,
    Fcmovne,
    Fcmovnu,
    Fcmovu,
    Fcom,
    Fcom2,
    Fcomi,
    Fcomip,
    Fcomp,
    Fcomp3,
    Fcomp5,
    Fcompp,
    Fcos,
    Fdecstp,
    Fdisi,
    Fdiv,
    Fdivp,
    Fdivr,
    Fdivrp,
    Feni,
    Ffree,
    Ffreep,
    Fiadd,
    Ficom,
    Ficomp,
    Fidiv,
    Fidivr,
    Fild,
    Fimul,
    Fincstp,
    Finit,
    Fist,
    Fistp,
    Fisttp,
    Fisub,
    Fisubr,
    Fld,
    Fld1,
    Fldcw,
    Fldenv,
    Fldl2e,
    Fldl2t,
    Fldlg2,
    Fldln2,
    Fldpi,
    Fldz,
    Fmul,
    Fmulp,
    Fnclex,
    Fndisi,
    Fneni,
    Fninit,
    Fnop,
    Fnsave,
    Fnsetpm,
    Fnstcw,
    Fnstenv,
    Fnstsw,
    Fpatan,
    Fprem,
    Fprem1,
    Fptan,
    Frndint,
    Frstor,
    Fsave,
    Fscale,
    Fsetpm,
    Fsin,
    Fsincos,
    Fsqrt,
    Fst,
    Fstcw,
    Fstenv,
    Fstp,
    Fstp1,
    Fstp8,
    Fstp9,
    Fstsw,
    Fsub,
    Fsubp,
    Fsubr,
    Fsubrp,
    Ftst,
    Fucom,
    Fucomi,
    Fucomip,
    Fucomp,
    Fucompp,
    Fwait,
    Fxam,
    Fxch,
    Fxch4,
    Fxch7,
    Fxrstor,
    Fxsave,
    Fxtract,
    Fyl2x,
    Fyl2xp1,
    Getsec,
    Haddpd,
    Haddps,
    HintNop,
    Hlt,
    Hsubpd,
    Hsubps,
    Icebp,
    Idiv,
    Imul,
    In,
    Inc,
    Ins,
    Insb,
    Insd,
    Insertps,
    Insw,
    Int,
    Int1,
    Into,
    Invd,
    Invept,
    Invlpg,
    Invvpid,
    Iret,
    Iretd,
    Iretq,
    Ja,
    Jae,
    Jb,
    Jbe,
    Jc,
    Jcxz,
    Je,
    Jecxz,
    Jg,
    Jge,
    Jl,
    Jle,
    Jmp,
    Jmpe,
    Jmpf,
    Jna,
    Jnae,
    Jnb,
    Jnbe,
    Jnc,
    Jne,
    Jng,
    Jnge,
    Jnl,
    Jnle,
    Jno,
    Jnp,
    Jns,
    Jnz,
    Jo,
    Jp,
    Jpe,
    Jpo,
    Jrcxz,
    Js,
    Jz,
    Lahf,
    Lar,
    Lddqu,
    Ldmxcsr,
    Lds,
    Lea,
    Leave,
    Les,
    Lfence,
    Lfs,
    Lgdt,
    Lgs,
    Lidt,
    Lldt,
    Lmsw,
    Loadall,
    Lods,
    Lodsb,
    Lodsd,
    Lodsq,
    Lodsw,
    Loop,
    Loope,
    Loopne,
    Loopnz,
    Loopz,
    Lsl,
    Lss,
    Ltr,
    Maskmovdqu,
    Maskmovq,
    Maxpd,
    Maxps,
    Maxsd,
    Maxss,
    Mfence,
    Minpd,
    Minps,
    Minsd,
    Minss,
    Monitor,
    Mov,
    Movapd,
    Movaps,
    Movbe,
    Movd,
    Movddup,
    Movdq2q,
    Movdqa,
    Movdqu,
    Movhlps,
    Movhpd,
    Movhps,
    Movlhps,
    Movlpd,
    Movlps,
    Movmskpd,
    Movmskps,
    Movntdq,
    Movntdqa,
    Movnti,
    Movntpd,
    Movntps,
    Movntq,
    Movq,
    Movq2dq,
    Movs,
    Movsb,
    Movsd,
    Movshdup,
    Movsldup,
    Movsq,
    Movss,
    Movsw,
    Movsx,
    Movsxd,
    Movupd,
    Movups,
    Movzx,
    Mpsadbw,
    Mul,
    Mulpd,
    Mulps,
    Mulsd,
    Mulss,
    Mwait,
    Neg,
    Nop,
    Not,
    Or,
    Orpd,
    Orps,
    Out,
    Outs,
    Outsb,
    Outsd,
    Outsw,
    Pabsb,
    Pabsd,
    Pabsw,
    Packssdw,
    Packsswb,
    Packusdw,
    Packuswb,
    Paddb,
    Paddd,
    Paddq,
    Paddsb,
    Paddsw,
    Paddusb,
    Paddusw,
    Paddw,
    Palignr,
    Pand,
    Pandn,
    Pause,
    Pavgb,
    Pavgw,
    Pblendvb,
    Pblendw,
    Pcmpeqb,
    Pcmpeqd,
    Pcmpeqq,
    Pcmpeqw,
    Pcmpestri,
    Pcmpestrm,
    Pcmpgtb,
    Pcmpgtd,
    Pcmpgtq,
    Pcmpgtw,
    Pcmpistri,
    Pcmpistrm,
    Pextrb,
    Pextrd,
    Pextrq,
    Pextrw,
    Phaddd,
    Phaddsw,
    Phaddw,
    Phminposuw,
    Phsubd,
    Phsubsw,
    Phsubw,
    Pinsrb,
    Pinsrd,
    Pinsrq,
    Pinsrw,
    Pmaddubsw,
    Pmaddwd,
    Pmaxsb,
    Pmaxsd,
    Pmaxsw,
    Pmaxub,
    Pmaxud,
    Pmaxuw,
    Pminsb,
    Pminsd,
    Pminsw,
    Pminub,
    Pminud,
    Pminuw,
    Pmovmskb,
    Pmovsxbd,
    Pmovsxbq,
    Pmovsxbw,
    Pmovsxdq,
    Pmovsxwd,
    Pmovsxwq,
    Pmovzxbd,
    Pmovzxbq,
    Pmovzxbw,
    Pmovzxdq,
    Pmovzxwd,
    Pmovzxwq,
    Pmuldq,
    Pmulhrsw,
    Pmulhuw,
    Pmulhw,
    Pmulld,
    Pmullw,
    Pmuludq,
    Pop,
    Popa,
    Popad,
    Popcnt,
    Popf,
    Popfd,
    Popfq,
    Por,
    Prefetchnta,
    Prefetcht0,
    Prefetcht1,
    Prefetcht2,
    Psadbw,
    Pshufb,
    Pshufd,
    Pshufhw,
    Pshuflw,
    Pshufw,
    Psignb,
    Psignd,
    Psignw,
    Pslld,
    Pslldq,
    Psllq,
    Psllw,
    Psrad,
    Psraw,
    Psrld,
    Psrldq,
    Psrlq,
    Psrlw,
    Psubb,
    Psubd,
    Psubq,
    Psubsb,
    Psubsw,
    Psubusb,
    Psubusw,
    Psubw,
    Ptest,
    Punpckhbw,
    Punpckhdq,
    Punpckhqdq,
    Punpckhwd,
    Punpcklbw,
    Punpckldq,
    Punpcklqdq,
    Punpcklwd,
    Push,
    Pusha,
    Pushad,
    Pushf,
    Pushfd,
    Pushfq,
    Pxor,
    Rcl,
    Rcpps,
    Rcpss,
    Rcr,
    Rdmsr,
    Rdpmc,
    Rdtsc,
    Rdtscp,
    Retf,
    Retn,
    Rol,
    Ror,
    Roundpd,
    Roundps,
    Roundsd,
    Roundss,
    Rsm,
    Rsqrtps,
    Rsqrtss,
    Sahf,
    Sal,
    Salc,
    Sar,
    Sbb,
    Scas,
    Scasb,
    Scasd,
    Scasq,
    Scasw,
    Seta,
    Setae,
    Setalc,
    Setb,
    Setbe,
    Setc,
    Sete,
    Setg,
    Setge,
    Setl,
    Setle,
    Setna,
    Setnae,
    Setnb,
    Setnbe,
    Setnc,
    Setne,
    Setng,
    Setnge,
    Setnl,
    Setnle,
    Setno,
    Setnp,
    Setns,
    Setnz,
    Seto,
    Setp,
    Setpe,
    Setpo,
    Sets,
    Setz,
    Sfence,
    Sgdt,
    Shl,
    Shld,
    Shr,
    Shrd,
    Shufpd,
    Shufps,
    Sidt,
    Sldt,
    Smsw,
    Sqrtpd,
    Sqrtps,
    Sqrtsd,
    Sqrtss,
    Stc,
    Std,
    Sti,
    Stmxcsr,
    Stos,
    Stosb,
    Stosd,
    Stosq,
    Stosw,
    Str,
    Sub,
    Subpd,
    Subps,
    Subsd,
    Subss,
    Swapgs,
    Syscall,
    Sysenter,
    Sysexit,
    Sysret,
    Test,
    Ucomisd,
    Ucomiss,
    Ud,
    Ud2,
    Unpckhpd,
    Unpckhps,
    Unpcklpd,
    Unpcklps,
    Verr,
    Verw,
    Vmcall,
    Vmclear,
    Vmlaunch,
    Vmptrld,
    Vmptrst,
    Vmread,
    Vmresume,
    Vmwrite,
    Vmxoff,
    Vmxon,
    Wait,
    Wbinvd,
    Wrmsr,
    Xadd,
    Xchg,
    Xgetbv,
    Xlat,
    Xlatb,
    Xor,
    Xorpd,
    Xorps,
    Xrstor,
    Xsave,
    Xsetbv,
}

#[macro_export]
macro_rules! x64_mnemonic {

    (aaa) => { $crate::x64::ast::Mnemonic::Aaa };
    (aad) => { $crate::x64::ast::Mnemonic::Aad };
    (aam) => { $crate::x64::ast::Mnemonic::Aam };
    (aas) => { $crate::x64::ast::Mnemonic::Aas };
    (adc) => { $crate::x64::ast::Mnemonic::Adc };
    (add) => { $crate::x64::ast::Mnemonic::Add };
    (addpd) => { $crate::x64::ast::Mnemonic::Addpd };
    (addps) => { $crate::x64::ast::Mnemonic::Addps };
    (addsd) => { $crate::x64::ast::Mnemonic::Addsd };
    (addss) => { $crate::x64::ast::Mnemonic::Addss };
    (addsubpd) => { $crate::x64::ast::Mnemonic::Addsubpd };
    (addsubps) => { $crate::x64::ast::Mnemonic::Addsubps };
    (adx) => { $crate::x64::ast::Mnemonic::Adx };
    (amx) => { $crate::x64::ast::Mnemonic::Amx };
    (and) => { $crate::x64::ast::Mnemonic::And };
    (andnpd) => { $crate::x64::ast::Mnemonic::Andnpd };
    (andnps) => { $crate::x64::ast::Mnemonic::Andnps };
    (andpd) => { $crate::x64::ast::Mnemonic::Andpd };
    (andps) => { $crate::x64::ast::Mnemonic::Andps };
    (arpl) => { $crate::x64::ast::Mnemonic::Arpl };
    (blendpd) => { $crate::x64::ast::Mnemonic::Blendpd };
    (blendps) => { $crate::x64::ast::Mnemonic::Blendps };
    (blendvpd) => { $crate::x64::ast::Mnemonic::Blendvpd };
    (blendvps) => { $crate::x64::ast::Mnemonic::Blendvps };
    (bound) => { $crate::x64::ast::Mnemonic::Bound };
    (bsf) => { $crate::x64::ast::Mnemonic::Bsf };
    (bsr) => { $crate::x64::ast::Mnemonic::Bsr };
    (bswap) => { $crate::x64::ast::Mnemonic::Bswap };
    (bt) => { $crate::x64::ast::Mnemonic::Bt };
    (btc) => { $crate::x64::ast::Mnemonic::Btc };
    (btr) => { $crate::x64::ast::Mnemonic::Btr };
    (bts) => { $crate::x64::ast::Mnemonic::Bts };
    (call) => { $crate::x64::ast::Mnemonic::Call };
    (callf) => { $crate::x64::ast::Mnemonic::Callf };
    (cbw) => { $crate::x64::ast::Mnemonic::Cbw };
    (cdq) => { $crate::x64::ast::Mnemonic::Cdq };
    (cdqe) => { $crate::x64::ast::Mnemonic::Cdqe };
    (clc) => { $crate::x64::ast::Mnemonic::Clc };
    (cld) => { $crate::x64::ast::Mnemonic::Cld };
    (clflush) => { $crate::x64::ast::Mnemonic::Clflush };
    (cli) => { $crate::x64::ast::Mnemonic::Cli };
    (clts) => { $crate::x64::ast::Mnemonic::Clts };
    (cmc) => { $crate::x64::ast::Mnemonic::Cmc };
    (cmova) => { $crate::x64::ast::Mnemonic::Cmova };
    (cmovae) => { $crate::x64::ast::Mnemonic::Cmovae };
    (cmovb) => { $crate::x64::ast::Mnemonic::Cmovb };
    (cmovbe) => { $crate::x64::ast::Mnemonic::Cmovbe };
    (cmovc) => { $crate::x64::ast::Mnemonic::Cmovc };
    (cmove) => { $crate::x64::ast::Mnemonic::Cmove };
    (cmovg) => { $crate::x64::ast::Mnemonic::Cmovg };
    (cmovge) => { $crate::x64::ast::Mnemonic::Cmovge };
    (cmovl) => { $crate::x64::ast::Mnemonic::Cmovl };
    (cmovle) => { $crate::x64::ast::Mnemonic::Cmovle };
    (cmovna) => { $crate::x64::ast::Mnemonic::Cmovna };
    (cmovnae) => { $crate::x64::ast::Mnemonic::Cmovnae };
    (cmovnb) => { $crate::x64::ast::Mnemonic::Cmovnb };
    (cmovnbe) => { $crate::x64::ast::Mnemonic::Cmovnbe };
    (cmovnc) => { $crate::x64::ast::Mnemonic::Cmovnc };
    (cmovne) => { $crate::x64::ast::Mnemonic::Cmovne };
    (cmovng) => { $crate::x64::ast::Mnemonic::Cmovng };
    (cmovnge) => { $crate::x64::ast::Mnemonic::Cmovnge };
    (cmovnl) => { $crate::x64::ast::Mnemonic::Cmovnl };
    (cmovnle) => { $crate::x64::ast::Mnemonic::Cmovnle };
    (cmovno) => { $crate::x64::ast::Mnemonic::Cmovno };
    (cmovnp) => { $crate::x64::ast::Mnemonic::Cmovnp };
    (cmovns) => { $crate::x64::ast::Mnemonic::Cmovns };
    (cmovnz) => { $crate::x64::ast::Mnemonic::Cmovnz };
    (cmovo) => { $crate::x64::ast::Mnemonic::Cmovo };
    (cmovp) => { $crate::x64::ast::Mnemonic::Cmovp };
    (cmovpe) => { $crate::x64::ast::Mnemonic::Cmovpe };
    (cmovpo) => { $crate::x64::ast::Mnemonic::Cmovpo };
    (cmovs) => { $crate::x64::ast::Mnemonic::Cmovs };
    (cmovz) => { $crate::x64::ast::Mnemonic::Cmovz };
    (cmp) => { $crate::x64::ast::Mnemonic::Cmp };
    (cmppd) => { $crate::x64::ast::Mnemonic::Cmppd };
    (cmpps) => { $crate::x64::ast::Mnemonic::Cmpps };
    (cmps) => { $crate::x64::ast::Mnemonic::Cmps };
    (cmpsb) => { $crate::x64::ast::Mnemonic::Cmpsb };
    (cmpsd) => { $crate::x64::ast::Mnemonic::Cmpsd };
    (cmpsq) => { $crate::x64::ast::Mnemonic::Cmpsq };
    (cmpss) => { $crate::x64::ast::Mnemonic::Cmpss };
    (cmpsw) => { $crate::x64::ast::Mnemonic::Cmpsw };
    (cmpxchg) => { $crate::x64::ast::Mnemonic::Cmpxchg };
    (cmpxchg16b) => { $crate::x64::ast::Mnemonic::Cmpxchg16b };
    (cmpxchg8b) => { $crate::x64::ast::Mnemonic::Cmpxchg8b };
    (comisd) => { $crate::x64::ast::Mnemonic::Comisd };
    (comiss) => { $crate::x64::ast::Mnemonic::Comiss };
    (cpuid) => { $crate::x64::ast::Mnemonic::Cpuid };
    (cqo) => { $crate::x64::ast::Mnemonic::Cqo };
    (crc32) => { $crate::x64::ast::Mnemonic::Crc32 };
    (cvtdq2pd) => { $crate::x64::ast::Mnemonic::Cvtdq2pd };
    (cvtdq2ps) => { $crate::x64::ast::Mnemonic::Cvtdq2ps };
    (cvtpd2dq) => { $crate::x64::ast::Mnemonic::Cvtpd2dq };
    (cvtpd2pi) => { $crate::x64::ast::Mnemonic::Cvtpd2pi };
    (cvtpd2ps) => { $crate::x64::ast::Mnemonic::Cvtpd2ps };
    (cvtpi2pd) => { $crate::x64::ast::Mnemonic::Cvtpi2pd };
    (cvtpi2ps) => { $crate::x64::ast::Mnemonic::Cvtpi2ps };
    (cvtps2dq) => { $crate::x64::ast::Mnemonic::Cvtps2dq };
    (cvtps2pd) => { $crate::x64::ast::Mnemonic::Cvtps2pd };
    (cvtps2pi) => { $crate::x64::ast::Mnemonic::Cvtps2pi };
    (cvtsd2si) => { $crate::x64::ast::Mnemonic::Cvtsd2si };
    (cvtsd2ss) => { $crate::x64::ast::Mnemonic::Cvtsd2ss };
    (cvtsi2sd) => { $crate::x64::ast::Mnemonic::Cvtsi2sd };
    (cvtsi2ss) => { $crate::x64::ast::Mnemonic::Cvtsi2ss };
    (cvtss2sd) => { $crate::x64::ast::Mnemonic::Cvtss2sd };
    (cvtss2si) => { $crate::x64::ast::Mnemonic::Cvtss2si };
    (cvttpd2dq) => { $crate::x64::ast::Mnemonic::Cvttpd2dq };
    (cvttpd2pi) => { $crate::x64::ast::Mnemonic::Cvttpd2pi };
    (cvttps2dq) => { $crate::x64::ast::Mnemonic::Cvttps2dq };
    (cvttps2pi) => { $crate::x64::ast::Mnemonic::Cvttps2pi };
    (cvttsd2si) => { $crate::x64::ast::Mnemonic::Cvttsd2si };
    (cvttss2si) => { $crate::x64::ast::Mnemonic::Cvttss2si };
    (cwd) => { $crate::x64::ast::Mnemonic::Cwd };
    (cwde) => { $crate::x64::ast::Mnemonic::Cwde };
    (daa) => { $crate::x64::ast::Mnemonic::Daa };
    (das) => { $crate::x64::ast::Mnemonic::Das };
    (dec) => { $crate::x64::ast::Mnemonic::Dec };
    (div) => { $crate::x64::ast::Mnemonic::Div };
    (divpd) => { $crate::x64::ast::Mnemonic::Divpd };
    (divps) => { $crate::x64::ast::Mnemonic::Divps };
    (divsd) => { $crate::x64::ast::Mnemonic::Divsd };
    (divss) => { $crate::x64::ast::Mnemonic::Divss };
    (dppd) => { $crate::x64::ast::Mnemonic::Dppd };
    (dpps) => { $crate::x64::ast::Mnemonic::Dpps };
    (emms) => { $crate::x64::ast::Mnemonic::Emms };
    (enter) => { $crate::x64::ast::Mnemonic::Enter };
    (extractps) => { $crate::x64::ast::Mnemonic::Extractps };
    (f2xm1) => { $crate::x64::ast::Mnemonic::F2xm1 };
    (fabs) => { $crate::x64::ast::Mnemonic::Fabs };
    (fadd) => { $crate::x64::ast::Mnemonic::Fadd };
    (faddp) => { $crate::x64::ast::Mnemonic::Faddp };
    (fbld) => { $crate::x64::ast::Mnemonic::Fbld };
    (fbstp) => { $crate::x64::ast::Mnemonic::Fbstp };
    (fchs) => { $crate::x64::ast::Mnemonic::Fchs };
    (fclex) => { $crate::x64::ast::Mnemonic::Fclex };
    (fcmovb) => { $crate::x64::ast::Mnemonic::Fcmovb };
    (fcmovbe) => { $crate::x64::ast::Mnemonic::Fcmovbe };
    (fcmove) => { $crate::x64::ast::Mnemonic::Fcmove };
    (fcmovnb) => { $crate::x64::ast::Mnemonic::Fcmovnb };
    (fcmovnbe) => { $crate::x64::ast::Mnemonic::Fcmovnbe };
    (fcmovne) => { $crate::x64::ast::Mnemonic::Fcmovne };
    (fcmovnu) => { $crate::x64::ast::Mnemonic::Fcmovnu };
    (fcmovu) => { $crate::x64::ast::Mnemonic::Fcmovu };
    (fcom) => { $crate::x64::ast::Mnemonic::Fcom };
    (fcom2) => { $crate::x64::ast::Mnemonic::Fcom2 };
    (fcomi) => { $crate::x64::ast::Mnemonic::Fcomi };
    (fcomip) => { $crate::x64::ast::Mnemonic::Fcomip };
    (fcomp) => { $crate::x64::ast::Mnemonic::Fcomp };
    (fcomp3) => { $crate::x64::ast::Mnemonic::Fcomp3 };
    (fcomp5) => { $crate::x64::ast::Mnemonic::Fcomp5 };
    (fcompp) => { $crate::x64::ast::Mnemonic::Fcompp };
    (fcos) => { $crate::x64::ast::Mnemonic::Fcos };
    (fdecstp) => { $crate::x64::ast::Mnemonic::Fdecstp };
    (fdisi) => { $crate::x64::ast::Mnemonic::Fdisi };
    (fdiv) => { $crate::x64::ast::Mnemonic::Fdiv };
    (fdivp) => { $crate::x64::ast::Mnemonic::Fdivp };
    (fdivr) => { $crate::x64::ast::Mnemonic::Fdivr };
    (fdivrp) => { $crate::x64::ast::Mnemonic::Fdivrp };
    (feni) => { $crate::x64::ast::Mnemonic::Feni };
    (ffree) => { $crate::x64::ast::Mnemonic::Ffree };
    (ffreep) => { $crate::x64::ast::Mnemonic::Ffreep };
    (fiadd) => { $crate::x64::ast::Mnemonic::Fiadd };
    (ficom) => { $crate::x64::ast::Mnemonic::Ficom };
    (ficomp) => { $crate::x64::ast::Mnemonic::Ficomp };
    (fidiv) => { $crate::x64::ast::Mnemonic::Fidiv };
    (fidivr) => { $crate::x64::ast::Mnemonic::Fidivr };
    (fild) => { $crate::x64::ast::Mnemonic::Fild };
    (fimul) => { $crate::x64::ast::Mnemonic::Fimul };
    (fincstp) => { $crate::x64::ast::Mnemonic::Fincstp };
    (finit) => { $crate::x64::ast::Mnemonic::Finit };
    (fist) => { $crate::x64::ast::Mnemonic::Fist };
    (fistp) => { $crate::x64::ast::Mnemonic::Fistp };
    (fisttp) => { $crate::x64::ast::Mnemonic::Fisttp };
    (fisub) => { $crate::x64::ast::Mnemonic::Fisub };
    (fisubr) => { $crate::x64::ast::Mnemonic::Fisubr };
    (fld) => { $crate::x64::ast::Mnemonic::Fld };
    (fld1) => { $crate::x64::ast::Mnemonic::Fld1 };
    (fldcw) => { $crate::x64::ast::Mnemonic::Fldcw };
    (fldenv) => { $crate::x64::ast::Mnemonic::Fldenv };
    (fldl2e) => { $crate::x64::ast::Mnemonic::Fldl2e };
    (fldl2t) => { $crate::x64::ast::Mnemonic::Fldl2t };
    (fldlg2) => { $crate::x64::ast::Mnemonic::Fldlg2 };
    (fldln2) => { $crate::x64::ast::Mnemonic::Fldln2 };
    (fldpi) => { $crate::x64::ast::Mnemonic::Fldpi };
    (fldz) => { $crate::x64::ast::Mnemonic::Fldz };
    (fmul) => { $crate::x64::ast::Mnemonic::Fmul };
    (fmulp) => { $crate::x64::ast::Mnemonic::Fmulp };
    (fnclex) => { $crate::x64::ast::Mnemonic::Fnclex };
    (fndisi) => { $crate::x64::ast::Mnemonic::Fndisi };
    (fneni) => { $crate::x64::ast::Mnemonic::Fneni };
    (fninit) => { $crate::x64::ast::Mnemonic::Fninit };
    (fnop) => { $crate::x64::ast::Mnemonic::Fnop };
    (fnsave) => { $crate::x64::ast::Mnemonic::Fnsave };
    (fnsetpm) => { $crate::x64::ast::Mnemonic::Fnsetpm };
    (fnstcw) => { $crate::x64::ast::Mnemonic::Fnstcw };
    (fnstenv) => { $crate::x64::ast::Mnemonic::Fnstenv };
    (fnstsw) => { $crate::x64::ast::Mnemonic::Fnstsw };
    (fpatan) => { $crate::x64::ast::Mnemonic::Fpatan };
    (fprem) => { $crate::x64::ast::Mnemonic::Fprem };
    (fprem1) => { $crate::x64::ast::Mnemonic::Fprem1 };
    (fptan) => { $crate::x64::ast::Mnemonic::Fptan };
    (frndint) => { $crate::x64::ast::Mnemonic::Frndint };
    (frstor) => { $crate::x64::ast::Mnemonic::Frstor };
    (fsave) => { $crate::x64::ast::Mnemonic::Fsave };
    (fscale) => { $crate::x64::ast::Mnemonic::Fscale };
    (fsetpm) => { $crate::x64::ast::Mnemonic::Fsetpm };
    (fsin) => { $crate::x64::ast::Mnemonic::Fsin };
    (fsincos) => { $crate::x64::ast::Mnemonic::Fsincos };
    (fsqrt) => { $crate::x64::ast::Mnemonic::Fsqrt };
    (fst) => { $crate::x64::ast::Mnemonic::Fst };
    (fstcw) => { $crate::x64::ast::Mnemonic::Fstcw };
    (fstenv) => { $crate::x64::ast::Mnemonic::Fstenv };
    (fstp) => { $crate::x64::ast::Mnemonic::Fstp };
    (fstp1) => { $crate::x64::ast::Mnemonic::Fstp1 };
    (fstp8) => { $crate::x64::ast::Mnemonic::Fstp8 };
    (fstp9) => { $crate::x64::ast::Mnemonic::Fstp9 };
    (fstsw) => { $crate::x64::ast::Mnemonic::Fstsw };
    (fsub) => { $crate::x64::ast::Mnemonic::Fsub };
    (fsubp) => { $crate::x64::ast::Mnemonic::Fsubp };
    (fsubr) => { $crate::x64::ast::Mnemonic::Fsubr };
    (fsubrp) => { $crate::x64::ast::Mnemonic::Fsubrp };
    (ftst) => { $crate::x64::ast::Mnemonic::Ftst };
    (fucom) => { $crate::x64::ast::Mnemonic::Fucom };
    (fucomi) => { $crate::x64::ast::Mnemonic::Fucomi };
    (fucomip) => { $crate::x64::ast::Mnemonic::Fucomip };
    (fucomp) => { $crate::x64::ast::Mnemonic::Fucomp };
    (fucompp) => { $crate::x64::ast::Mnemonic::Fucompp };
    (fwait) => { $crate::x64::ast::Mnemonic::Fwait };
    (fxam) => { $crate::x64::ast::Mnemonic::Fxam };
    (fxch) => { $crate::x64::ast::Mnemonic::Fxch };
    (fxch4) => { $crate::x64::ast::Mnemonic::Fxch4 };
    (fxch7) => { $crate::x64::ast::Mnemonic::Fxch7 };
    (fxrstor) => { $crate::x64::ast::Mnemonic::Fxrstor };
    (fxsave) => { $crate::x64::ast::Mnemonic::Fxsave };
    (fxtract) => { $crate::x64::ast::Mnemonic::Fxtract };
    (fyl2x) => { $crate::x64::ast::Mnemonic::Fyl2x };
    (fyl2xp1) => { $crate::x64::ast::Mnemonic::Fyl2xp1 };
    (getsec) => { $crate::x64::ast::Mnemonic::Getsec };
    (haddpd) => { $crate::x64::ast::Mnemonic::Haddpd };
    (haddps) => { $crate::x64::ast::Mnemonic::Haddps };
    (hint_nop) => { $crate::x64::ast::Mnemonic::HintNop };
    (hlt) => { $crate::x64::ast::Mnemonic::Hlt };
    (hsubpd) => { $crate::x64::ast::Mnemonic::Hsubpd };
    (hsubps) => { $crate::x64::ast::Mnemonic::Hsubps };
    (icebp) => { $crate::x64::ast::Mnemonic::Icebp };
    (idiv) => { $crate::x64::ast::Mnemonic::Idiv };
    (imul) => { $crate::x64::ast::Mnemonic::Imul };
    (in) => { $crate::x64::ast::Mnemonic::In };
    (inc) => { $crate::x64::ast::Mnemonic::Inc };
    (ins) => { $crate::x64::ast::Mnemonic::Ins };
    (insb) => { $crate::x64::ast::Mnemonic::Insb };
    (insd) => { $crate::x64::ast::Mnemonic::Insd };
    (insertps) => { $crate::x64::ast::Mnemonic::Insertps };
    (insw) => { $crate::x64::ast::Mnemonic::Insw };
    (int) => { $crate::x64::ast::Mnemonic::Int };
    (int1) => { $crate::x64::ast::Mnemonic::Int1 };
    (into) => { $crate::x64::ast::Mnemonic::Into };
    (invd) => { $crate::x64::ast::Mnemonic::Invd };
    (invept) => { $crate::x64::ast::Mnemonic::Invept };
    (invlpg) => { $crate::x64::ast::Mnemonic::Invlpg };
    (invvpid) => { $crate::x64::ast::Mnemonic::Invvpid };
    (iret) => { $crate::x64::ast::Mnemonic::Iret };
    (iretd) => { $crate::x64::ast::Mnemonic::Iretd };
    (iretq) => { $crate::x64::ast::Mnemonic::Iretq };
    (ja) => { $crate::x64::ast::Mnemonic::Ja };
    (jae) => { $crate::x64::ast::Mnemonic::Jae };
    (jb) => { $crate::x64::ast::Mnemonic::Jb };
    (jbe) => { $crate::x64::ast::Mnemonic::Jbe };
    (jc) => { $crate::x64::ast::Mnemonic::Jc };
    (jcxz) => { $crate::x64::ast::Mnemonic::Jcxz };
    (je) => { $crate::x64::ast::Mnemonic::Je };
    (jecxz) => { $crate::x64::ast::Mnemonic::Jecxz };
    (jg) => { $crate::x64::ast::Mnemonic::Jg };
    (jge) => { $crate::x64::ast::Mnemonic::Jge };
    (jl) => { $crate::x64::ast::Mnemonic::Jl };
    (jle) => { $crate::x64::ast::Mnemonic::Jle };
    (jmp) => { $crate::x64::ast::Mnemonic::Jmp };
    (jmpe) => { $crate::x64::ast::Mnemonic::Jmpe };
    (jmpf) => { $crate::x64::ast::Mnemonic::Jmpf };
    (jna) => { $crate::x64::ast::Mnemonic::Jna };
    (jnae) => { $crate::x64::ast::Mnemonic::Jnae };
    (jnb) => { $crate::x64::ast::Mnemonic::Jnb };
    (jnbe) => { $crate::x64::ast::Mnemonic::Jnbe };
    (jnc) => { $crate::x64::ast::Mnemonic::Jnc };
    (jne) => { $crate::x64::ast::Mnemonic::Jne };
    (jng) => { $crate::x64::ast::Mnemonic::Jng };
    (jnge) => { $crate::x64::ast::Mnemonic::Jnge };
    (jnl) => { $crate::x64::ast::Mnemonic::Jnl };
    (jnle) => { $crate::x64::ast::Mnemonic::Jnle };
    (jno) => { $crate::x64::ast::Mnemonic::Jno };
    (jnp) => { $crate::x64::ast::Mnemonic::Jnp };
    (jns) => { $crate::x64::ast::Mnemonic::Jns };
    (jnz) => { $crate::x64::ast::Mnemonic::Jnz };
    (jo) => { $crate::x64::ast::Mnemonic::Jo };
    (jp) => { $crate::x64::ast::Mnemonic::Jp };
    (jpe) => { $crate::x64::ast::Mnemonic::Jpe };
    (jpo) => { $crate::x64::ast::Mnemonic::Jpo };
    (jrcxz) => { $crate::x64::ast::Mnemonic::Jrcxz };
    (js) => { $crate::x64::ast::Mnemonic::Js };
    (jz) => { $crate::x64::ast::Mnemonic::Jz };
    (lahf) => { $crate::x64::ast::Mnemonic::Lahf };
    (lar) => { $crate::x64::ast::Mnemonic::Lar };
    (lddqu) => { $crate::x64::ast::Mnemonic::Lddqu };
    (ldmxcsr) => { $crate::x64::ast::Mnemonic::Ldmxcsr };
    (lds) => { $crate::x64::ast::Mnemonic::Lds };
    (lea) => { $crate::x64::ast::Mnemonic::Lea };
    (leave) => { $crate::x64::ast::Mnemonic::Leave };
    (les) => { $crate::x64::ast::Mnemonic::Les };
    (lfence) => { $crate::x64::ast::Mnemonic::Lfence };
    (lfs) => { $crate::x64::ast::Mnemonic::Lfs };
    (lgdt) => { $crate::x64::ast::Mnemonic::Lgdt };
    (lgs) => { $crate::x64::ast::Mnemonic::Lgs };
    (lidt) => { $crate::x64::ast::Mnemonic::Lidt };
    (lldt) => { $crate::x64::ast::Mnemonic::Lldt };
    (lmsw) => { $crate::x64::ast::Mnemonic::Lmsw };
    (loadall) => { $crate::x64::ast::Mnemonic::Loadall };
    (lods) => { $crate::x64::ast::Mnemonic::Lods };
    (lodsb) => { $crate::x64::ast::Mnemonic::Lodsb };
    (lodsd) => { $crate::x64::ast::Mnemonic::Lodsd };
    (lodsq) => { $crate::x64::ast::Mnemonic::Lodsq };
    (lodsw) => { $crate::x64::ast::Mnemonic::Lodsw };
    (loop) => { $crate::x64::ast::Mnemonic::Loop };
    (loope) => { $crate::x64::ast::Mnemonic::Loope };
    (loopne) => { $crate::x64::ast::Mnemonic::Loopne };
    (loopnz) => { $crate::x64::ast::Mnemonic::Loopnz };
    (loopz) => { $crate::x64::ast::Mnemonic::Loopz };
    (lsl) => { $crate::x64::ast::Mnemonic::Lsl };
    (lss) => { $crate::x64::ast::Mnemonic::Lss };
    (ltr) => { $crate::x64::ast::Mnemonic::Ltr };
    (maskmovdqu) => { $crate::x64::ast::Mnemonic::Maskmovdqu };
    (maskmovq) => { $crate::x64::ast::Mnemonic::Maskmovq };
    (maxpd) => { $crate::x64::ast::Mnemonic::Maxpd };
    (maxps) => { $crate::x64::ast::Mnemonic::Maxps };
    (maxsd) => { $crate::x64::ast::Mnemonic::Maxsd };
    (maxss) => { $crate::x64::ast::Mnemonic::Maxss };
    (mfence) => { $crate::x64::ast::Mnemonic::Mfence };
    (minpd) => { $crate::x64::ast::Mnemonic::Minpd };
    (minps) => { $crate::x64::ast::Mnemonic::Minps };
    (minsd) => { $crate::x64::ast::Mnemonic::Minsd };
    (minss) => { $crate::x64::ast::Mnemonic::Minss };
    (monitor) => { $crate::x64::ast::Mnemonic::Monitor };
    (mov) => { $crate::x64::ast::Mnemonic::Mov };
    (movapd) => { $crate::x64::ast::Mnemonic::Movapd };
    (movaps) => { $crate::x64::ast::Mnemonic::Movaps };
    (movbe) => { $crate::x64::ast::Mnemonic::Movbe };
    (movd) => { $crate::x64::ast::Mnemonic::Movd };
    (movddup) => { $crate::x64::ast::Mnemonic::Movddup };
    (movdq2q) => { $crate::x64::ast::Mnemonic::Movdq2q };
    (movdqa) => { $crate::x64::ast::Mnemonic::Movdqa };
    (movdqu) => { $crate::x64::ast::Mnemonic::Movdqu };
    (movhlps) => { $crate::x64::ast::Mnemonic::Movhlps };
    (movhpd) => { $crate::x64::ast::Mnemonic::Movhpd };
    (movhps) => { $crate::x64::ast::Mnemonic::Movhps };
    (movlhps) => { $crate::x64::ast::Mnemonic::Movlhps };
    (movlpd) => { $crate::x64::ast::Mnemonic::Movlpd };
    (movlps) => { $crate::x64::ast::Mnemonic::Movlps };
    (movmskpd) => { $crate::x64::ast::Mnemonic::Movmskpd };
    (movmskps) => { $crate::x64::ast::Mnemonic::Movmskps };
    (movntdq) => { $crate::x64::ast::Mnemonic::Movntdq };
    (movntdqa) => { $crate::x64::ast::Mnemonic::Movntdqa };
    (movnti) => { $crate::x64::ast::Mnemonic::Movnti };
    (movntpd) => { $crate::x64::ast::Mnemonic::Movntpd };
    (movntps) => { $crate::x64::ast::Mnemonic::Movntps };
    (movntq) => { $crate::x64::ast::Mnemonic::Movntq };
    (movq) => { $crate::x64::ast::Mnemonic::Movq };
    (movq2dq) => { $crate::x64::ast::Mnemonic::Movq2dq };
    (movs) => { $crate::x64::ast::Mnemonic::Movs };
    (movsb) => { $crate::x64::ast::Mnemonic::Movsb };
    (movsd) => { $crate::x64::ast::Mnemonic::Movsd };
    (movshdup) => { $crate::x64::ast::Mnemonic::Movshdup };
    (movsldup) => { $crate::x64::ast::Mnemonic::Movsldup };
    (movsq) => { $crate::x64::ast::Mnemonic::Movsq };
    (movss) => { $crate::x64::ast::Mnemonic::Movss };
    (movsw) => { $crate::x64::ast::Mnemonic::Movsw };
    (movsx) => { $crate::x64::ast::Mnemonic::Movsx };
    (movsxd) => { $crate::x64::ast::Mnemonic::Movsxd };
    (movupd) => { $crate::x64::ast::Mnemonic::Movupd };
    (movups) => { $crate::x64::ast::Mnemonic::Movups };
    (movzx) => { $crate::x64::ast::Mnemonic::Movzx };
    (mpsadbw) => { $crate::x64::ast::Mnemonic::Mpsadbw };
    (mul) => { $crate::x64::ast::Mnemonic::Mul };
    (mulpd) => { $crate::x64::ast::Mnemonic::Mulpd };
    (mulps) => { $crate::x64::ast::Mnemonic::Mulps };
    (mulsd) => { $crate::x64::ast::Mnemonic::Mulsd };
    (mulss) => { $crate::x64::ast::Mnemonic::Mulss };
    (mwait) => { $crate::x64::ast::Mnemonic::Mwait };
    (neg) => { $crate::x64::ast::Mnemonic::Neg };
    (nop) => { $crate::x64::ast::Mnemonic::Nop };
    (not) => { $crate::x64::ast::Mnemonic::Not };
    (or) => { $crate::x64::ast::Mnemonic::Or };
    (orpd) => { $crate::x64::ast::Mnemonic::Orpd };
    (orps) => { $crate::x64::ast::Mnemonic::Orps };
    (out) => { $crate::x64::ast::Mnemonic::Out };
    (outs) => { $crate::x64::ast::Mnemonic::Outs };
    (outsb) => { $crate::x64::ast::Mnemonic::Outsb };
    (outsd) => { $crate::x64::ast::Mnemonic::Outsd };
    (outsw) => { $crate::x64::ast::Mnemonic::Outsw };
    (pabsb) => { $crate::x64::ast::Mnemonic::Pabsb };
    (pabsd) => { $crate::x64::ast::Mnemonic::Pabsd };
    (pabsw) => { $crate::x64::ast::Mnemonic::Pabsw };
    (packssdw) => { $crate::x64::ast::Mnemonic::Packssdw };
    (packsswb) => { $crate::x64::ast::Mnemonic::Packsswb };
    (packusdw) => { $crate::x64::ast::Mnemonic::Packusdw };
    (packuswb) => { $crate::x64::ast::Mnemonic::Packuswb };
    (paddb) => { $crate::x64::ast::Mnemonic::Paddb };
    (paddd) => { $crate::x64::ast::Mnemonic::Paddd };
    (paddq) => { $crate::x64::ast::Mnemonic::Paddq };
    (paddsb) => { $crate::x64::ast::Mnemonic::Paddsb };
    (paddsw) => { $crate::x64::ast::Mnemonic::Paddsw };
    (paddusb) => { $crate::x64::ast::Mnemonic::Paddusb };
    (paddusw) => { $crate::x64::ast::Mnemonic::Paddusw };
    (paddw) => { $crate::x64::ast::Mnemonic::Paddw };
    (palignr) => { $crate::x64::ast::Mnemonic::Palignr };
    (pand) => { $crate::x64::ast::Mnemonic::Pand };
    (pandn) => { $crate::x64::ast::Mnemonic::Pandn };
    (pause) => { $crate::x64::ast::Mnemonic::Pause };
    (pavgb) => { $crate::x64::ast::Mnemonic::Pavgb };
    (pavgw) => { $crate::x64::ast::Mnemonic::Pavgw };
    (pblendvb) => { $crate::x64::ast::Mnemonic::Pblendvb };
    (pblendw) => { $crate::x64::ast::Mnemonic::Pblendw };
    (pcmpeqb) => { $crate::x64::ast::Mnemonic::Pcmpeqb };
    (pcmpeqd) => { $crate::x64::ast::Mnemonic::Pcmpeqd };
    (pcmpeqq) => { $crate::x64::ast::Mnemonic::Pcmpeqq };
    (pcmpeqw) => { $crate::x64::ast::Mnemonic::Pcmpeqw };
    (pcmpestri) => { $crate::x64::ast::Mnemonic::Pcmpestri };
    (pcmpestrm) => { $crate::x64::ast::Mnemonic::Pcmpestrm };
    (pcmpgtb) => { $crate::x64::ast::Mnemonic::Pcmpgtb };
    (pcmpgtd) => { $crate::x64::ast::Mnemonic::Pcmpgtd };
    (pcmpgtq) => { $crate::x64::ast::Mnemonic::Pcmpgtq };
    (pcmpgtw) => { $crate::x64::ast::Mnemonic::Pcmpgtw };
    (pcmpistri) => { $crate::x64::ast::Mnemonic::Pcmpistri };
    (pcmpistrm) => { $crate::x64::ast::Mnemonic::Pcmpistrm };
    (pextrb) => { $crate::x64::ast::Mnemonic::Pextrb };
    (pextrd) => { $crate::x64::ast::Mnemonic::Pextrd };
    (pextrq) => { $crate::x64::ast::Mnemonic::Pextrq };
    (pextrw) => { $crate::x64::ast::Mnemonic::Pextrw };
    (phaddd) => { $crate::x64::ast::Mnemonic::Phaddd };
    (phaddsw) => { $crate::x64::ast::Mnemonic::Phaddsw };
    (phaddw) => { $crate::x64::ast::Mnemonic::Phaddw };
    (phminposuw) => { $crate::x64::ast::Mnemonic::Phminposuw };
    (phsubd) => { $crate::x64::ast::Mnemonic::Phsubd };
    (phsubsw) => { $crate::x64::ast::Mnemonic::Phsubsw };
    (phsubw) => { $crate::x64::ast::Mnemonic::Phsubw };
    (pinsrb) => { $crate::x64::ast::Mnemonic::Pinsrb };
    (pinsrd) => { $crate::x64::ast::Mnemonic::Pinsrd };
    (pinsrq) => { $crate::x64::ast::Mnemonic::Pinsrq };
    (pinsrw) => { $crate::x64::ast::Mnemonic::Pinsrw };
    (pmaddubsw) => { $crate::x64::ast::Mnemonic::Pmaddubsw };
    (pmaddwd) => { $crate::x64::ast::Mnemonic::Pmaddwd };
    (pmaxsb) => { $crate::x64::ast::Mnemonic::Pmaxsb };
    (pmaxsd) => { $crate::x64::ast::Mnemonic::Pmaxsd };
    (pmaxsw) => { $crate::x64::ast::Mnemonic::Pmaxsw };
    (pmaxub) => { $crate::x64::ast::Mnemonic::Pmaxub };
    (pmaxud) => { $crate::x64::ast::Mnemonic::Pmaxud };
    (pmaxuw) => { $crate::x64::ast::Mnemonic::Pmaxuw };
    (pminsb) => { $crate::x64::ast::Mnemonic::Pminsb };
    (pminsd) => { $crate::x64::ast::Mnemonic::Pminsd };
    (pminsw) => { $crate::x64::ast::Mnemonic::Pminsw };
    (pminub) => { $crate::x64::ast::Mnemonic::Pminub };
    (pminud) => { $crate::x64::ast::Mnemonic::Pminud };
    (pminuw) => { $crate::x64::ast::Mnemonic::Pminuw };
    (pmovmskb) => { $crate::x64::ast::Mnemonic::Pmovmskb };
    (pmovsxbd) => { $crate::x64::ast::Mnemonic::Pmovsxbd };
    (pmovsxbq) => { $crate::x64::ast::Mnemonic::Pmovsxbq };
    (pmovsxbw) => { $crate::x64::ast::Mnemonic::Pmovsxbw };
    (pmovsxdq) => { $crate::x64::ast::Mnemonic::Pmovsxdq };
    (pmovsxwd) => { $crate::x64::ast::Mnemonic::Pmovsxwd };
    (pmovsxwq) => { $crate::x64::ast::Mnemonic::Pmovsxwq };
    (pmovzxbd) => { $crate::x64::ast::Mnemonic::Pmovzxbd };
    (pmovzxbq) => { $crate::x64::ast::Mnemonic::Pmovzxbq };
    (pmovzxbw) => { $crate::x64::ast::Mnemonic::Pmovzxbw };
    (pmovzxdq) => { $crate::x64::ast::Mnemonic::Pmovzxdq };
    (pmovzxwd) => { $crate::x64::ast::Mnemonic::Pmovzxwd };
    (pmovzxwq) => { $crate::x64::ast::Mnemonic::Pmovzxwq };
    (pmuldq) => { $crate::x64::ast::Mnemonic::Pmuldq };
    (pmulhrsw) => { $crate::x64::ast::Mnemonic::Pmulhrsw };
    (pmulhuw) => { $crate::x64::ast::Mnemonic::Pmulhuw };
    (pmulhw) => { $crate::x64::ast::Mnemonic::Pmulhw };
    (pmulld) => { $crate::x64::ast::Mnemonic::Pmulld };
    (pmullw) => { $crate::x64::ast::Mnemonic::Pmullw };
    (pmuludq) => { $crate::x64::ast::Mnemonic::Pmuludq };
    (pop) => { $crate::x64::ast::Mnemonic::Pop };
    (popa) => { $crate::x64::ast::Mnemonic::Popa };
    (popad) => { $crate::x64::ast::Mnemonic::Popad };
    (popcnt) => { $crate::x64::ast::Mnemonic::Popcnt };
    (popf) => { $crate::x64::ast::Mnemonic::Popf };
    (popfd) => { $crate::x64::ast::Mnemonic::Popfd };
    (popfq) => { $crate::x64::ast::Mnemonic::Popfq };
    (por) => { $crate::x64::ast::Mnemonic::Por };
    (prefetchnta) => { $crate::x64::ast::Mnemonic::Prefetchnta };
    (prefetcht0) => { $crate::x64::ast::Mnemonic::Prefetcht0 };
    (prefetcht1) => { $crate::x64::ast::Mnemonic::Prefetcht1 };
    (prefetcht2) => { $crate::x64::ast::Mnemonic::Prefetcht2 };
    (psadbw) => { $crate::x64::ast::Mnemonic::Psadbw };
    (pshufb) => { $crate::x64::ast::Mnemonic::Pshufb };
    (pshufd) => { $crate::x64::ast::Mnemonic::Pshufd };
    (pshufhw) => { $crate::x64::ast::Mnemonic::Pshufhw };
    (pshuflw) => { $crate::x64::ast::Mnemonic::Pshuflw };
    (pshufw) => { $crate::x64::ast::Mnemonic::Pshufw };
    (psignb) => { $crate::x64::ast::Mnemonic::Psignb };
    (psignd) => { $crate::x64::ast::Mnemonic::Psignd };
    (psignw) => { $crate::x64::ast::Mnemonic::Psignw };
    (pslld) => { $crate::x64::ast::Mnemonic::Pslld };
    (pslldq) => { $crate::x64::ast::Mnemonic::Pslldq };
    (psllq) => { $crate::x64::ast::Mnemonic::Psllq };
    (psllw) => { $crate::x64::ast::Mnemonic::Psllw };
    (psrad) => { $crate::x64::ast::Mnemonic::Psrad };
    (psraw) => { $crate::x64::ast::Mnemonic::Psraw };
    (psrld) => { $crate::x64::ast::Mnemonic::Psrld };
    (psrldq) => { $crate::x64::ast::Mnemonic::Psrldq };
    (psrlq) => { $crate::x64::ast::Mnemonic::Psrlq };
    (psrlw) => { $crate::x64::ast::Mnemonic::Psrlw };
    (psubb) => { $crate::x64::ast::Mnemonic::Psubb };
    (psubd) => { $crate::x64::ast::Mnemonic::Psubd };
    (psubq) => { $crate::x64::ast::Mnemonic::Psubq };
    (psubsb) => { $crate::x64::ast::Mnemonic::Psubsb };
    (psubsw) => { $crate::x64::ast::Mnemonic::Psubsw };
    (psubusb) => { $crate::x64::ast::Mnemonic::Psubusb };
    (psubusw) => { $crate::x64::ast::Mnemonic::Psubusw };
    (psubw) => { $crate::x64::ast::Mnemonic::Psubw };
    (ptest) => { $crate::x64::ast::Mnemonic::Ptest };
    (punpckhbw) => { $crate::x64::ast::Mnemonic::Punpckhbw };
    (punpckhdq) => { $crate::x64::ast::Mnemonic::Punpckhdq };
    (punpckhqdq) => { $crate::x64::ast::Mnemonic::Punpckhqdq };
    (punpckhwd) => { $crate::x64::ast::Mnemonic::Punpckhwd };
    (punpcklbw) => { $crate::x64::ast::Mnemonic::Punpcklbw };
    (punpckldq) => { $crate::x64::ast::Mnemonic::Punpckldq };
    (punpcklqdq) => { $crate::x64::ast::Mnemonic::Punpcklqdq };
    (punpcklwd) => { $crate::x64::ast::Mnemonic::Punpcklwd };
    (push) => { $crate::x64::ast::Mnemonic::Push };
    (pusha) => { $crate::x64::ast::Mnemonic::Pusha };
    (pushad) => { $crate::x64::ast::Mnemonic::Pushad };
    (pushf) => { $crate::x64::ast::Mnemonic::Pushf };
    (pushfd) => { $crate::x64::ast::Mnemonic::Pushfd };
    (pushfq) => { $crate::x64::ast::Mnemonic::Pushfq };
    (pxor) => { $crate::x64::ast::Mnemonic::Pxor };
    (rcl) => { $crate::x64::ast::Mnemonic::Rcl };
    (rcpps) => { $crate::x64::ast::Mnemonic::Rcpps };
    (rcpss) => { $crate::x64::ast::Mnemonic::Rcpss };
    (rcr) => { $crate::x64::ast::Mnemonic::Rcr };
    (rdmsr) => { $crate::x64::ast::Mnemonic::Rdmsr };
    (rdpmc) => { $crate::x64::ast::Mnemonic::Rdpmc };
    (rdtsc) => { $crate::x64::ast::Mnemonic::Rdtsc };
    (rdtscp) => { $crate::x64::ast::Mnemonic::Rdtscp };
    (retf) => { $crate::x64::ast::Mnemonic::Retf };
    (retn) => { $crate::x64::ast::Mnemonic::Retn };
    (rol) => { $crate::x64::ast::Mnemonic::Rol };
    (ror) => { $crate::x64::ast::Mnemonic::Ror };
    (roundpd) => { $crate::x64::ast::Mnemonic::Roundpd };
    (roundps) => { $crate::x64::ast::Mnemonic::Roundps };
    (roundsd) => { $crate::x64::ast::Mnemonic::Roundsd };
    (roundss) => { $crate::x64::ast::Mnemonic::Roundss };
    (rsm) => { $crate::x64::ast::Mnemonic::Rsm };
    (rsqrtps) => { $crate::x64::ast::Mnemonic::Rsqrtps };
    (rsqrtss) => { $crate::x64::ast::Mnemonic::Rsqrtss };
    (sahf) => { $crate::x64::ast::Mnemonic::Sahf };
    (sal) => { $crate::x64::ast::Mnemonic::Sal };
    (salc) => { $crate::x64::ast::Mnemonic::Salc };
    (sar) => { $crate::x64::ast::Mnemonic::Sar };
    (sbb) => { $crate::x64::ast::Mnemonic::Sbb };
    (scas) => { $crate::x64::ast::Mnemonic::Scas };
    (scasb) => { $crate::x64::ast::Mnemonic::Scasb };
    (scasd) => { $crate::x64::ast::Mnemonic::Scasd };
    (scasq) => { $crate::x64::ast::Mnemonic::Scasq };
    (scasw) => { $crate::x64::ast::Mnemonic::Scasw };
    (seta) => { $crate::x64::ast::Mnemonic::Seta };
    (setae) => { $crate::x64::ast::Mnemonic::Setae };
    (setalc) => { $crate::x64::ast::Mnemonic::Setalc };
    (setb) => { $crate::x64::ast::Mnemonic::Setb };
    (setbe) => { $crate::x64::ast::Mnemonic::Setbe };
    (setc) => { $crate::x64::ast::Mnemonic::Setc };
    (sete) => { $crate::x64::ast::Mnemonic::Sete };
    (setg) => { $crate::x64::ast::Mnemonic::Setg };
    (setge) => { $crate::x64::ast::Mnemonic::Setge };
    (setl) => { $crate::x64::ast::Mnemonic::Setl };
    (setle) => { $crate::x64::ast::Mnemonic::Setle };
    (setna) => { $crate::x64::ast::Mnemonic::Setna };
    (setnae) => { $crate::x64::ast::Mnemonic::Setnae };
    (setnb) => { $crate::x64::ast::Mnemonic::Setnb };
    (setnbe) => { $crate::x64::ast::Mnemonic::Setnbe };
    (setnc) => { $crate::x64::ast::Mnemonic::Setnc };
    (setne) => { $crate::x64::ast::Mnemonic::Setne };
    (setng) => { $crate::x64::ast::Mnemonic::Setng };
    (setnge) => { $crate::x64::ast::Mnemonic::Setnge };
    (setnl) => { $crate::x64::ast::Mnemonic::Setnl };
    (setnle) => { $crate::x64::ast::Mnemonic::Setnle };
    (setno) => { $crate::x64::ast::Mnemonic::Setno };
    (setnp) => { $crate::x64::ast::Mnemonic::Setnp };
    (setns) => { $crate::x64::ast::Mnemonic::Setns };
    (setnz) => { $crate::x64::ast::Mnemonic::Setnz };
    (seto) => { $crate::x64::ast::Mnemonic::Seto };
    (setp) => { $crate::x64::ast::Mnemonic::Setp };
    (setpe) => { $crate::x64::ast::Mnemonic::Setpe };
    (setpo) => { $crate::x64::ast::Mnemonic::Setpo };
    (sets) => { $crate::x64::ast::Mnemonic::Sets };
    (setz) => { $crate::x64::ast::Mnemonic::Setz };
    (sfence) => { $crate::x64::ast::Mnemonic::Sfence };
    (sgdt) => { $crate::x64::ast::Mnemonic::Sgdt };
    (shl) => { $crate::x64::ast::Mnemonic::Shl };
    (shld) => { $crate::x64::ast::Mnemonic::Shld };
    (shr) => { $crate::x64::ast::Mnemonic::Shr };
    (shrd) => { $crate::x64::ast::Mnemonic::Shrd };
    (shufpd) => { $crate::x64::ast::Mnemonic::Shufpd };
    (shufps) => { $crate::x64::ast::Mnemonic::Shufps };
    (sidt) => { $crate::x64::ast::Mnemonic::Sidt };
    (sldt) => { $crate::x64::ast::Mnemonic::Sldt };
    (smsw) => { $crate::x64::ast::Mnemonic::Smsw };
    (sqrtpd) => { $crate::x64::ast::Mnemonic::Sqrtpd };
    (sqrtps) => { $crate::x64::ast::Mnemonic::Sqrtps };
    (sqrtsd) => { $crate::x64::ast::Mnemonic::Sqrtsd };
    (sqrtss) => { $crate::x64::ast::Mnemonic::Sqrtss };
    (stc) => { $crate::x64::ast::Mnemonic::Stc };
    (std) => { $crate::x64::ast::Mnemonic::Std };
    (sti) => { $crate::x64::ast::Mnemonic::Sti };
    (stmxcsr) => { $crate::x64::ast::Mnemonic::Stmxcsr };
    (stos) => { $crate::x64::ast::Mnemonic::Stos };
    (stosb) => { $crate::x64::ast::Mnemonic::Stosb };
    (stosd) => { $crate::x64::ast::Mnemonic::Stosd };
    (stosq) => { $crate::x64::ast::Mnemonic::Stosq };
    (stosw) => { $crate::x64::ast::Mnemonic::Stosw };
    (str) => { $crate::x64::ast::Mnemonic::Str };
    (sub) => { $crate::x64::ast::Mnemonic::Sub };
    (subpd) => { $crate::x64::ast::Mnemonic::Subpd };
    (subps) => { $crate::x64::ast::Mnemonic::Subps };
    (subsd) => { $crate::x64::ast::Mnemonic::Subsd };
    (subss) => { $crate::x64::ast::Mnemonic::Subss };
    (swapgs) => { $crate::x64::ast::Mnemonic::Swapgs };
    (syscall) => { $crate::x64::ast::Mnemonic::Syscall };
    (sysenter) => { $crate::x64::ast::Mnemonic::Sysenter };
    (sysexit) => { $crate::x64::ast::Mnemonic::Sysexit };
    (sysret) => { $crate::x64::ast::Mnemonic::Sysret };
    (test) => { $crate::x64::ast::Mnemonic::Test };
    (ucomisd) => { $crate::x64::ast::Mnemonic::Ucomisd };
    (ucomiss) => { $crate::x64::ast::Mnemonic::Ucomiss };
    (ud) => { $crate::x64::ast::Mnemonic::Ud };
    (ud2) => { $crate::x64::ast::Mnemonic::Ud2 };
    (unpckhpd) => { $crate::x64::ast::Mnemonic::Unpckhpd };
    (unpckhps) => { $crate::x64::ast::Mnemonic::Unpckhps };
    (unpcklpd) => { $crate::x64::ast::Mnemonic::Unpcklpd };
    (unpcklps) => { $crate::x64::ast::Mnemonic::Unpcklps };
    (verr) => { $crate::x64::ast::Mnemonic::Verr };
    (verw) => { $crate::x64::ast::Mnemonic::Verw };
    (vmcall) => { $crate::x64::ast::Mnemonic::Vmcall };
    (vmclear) => { $crate::x64::ast::Mnemonic::Vmclear };
    (vmlaunch) => { $crate::x64::ast::Mnemonic::Vmlaunch };
    (vmptrld) => { $crate::x64::ast::Mnemonic::Vmptrld };
    (vmptrst) => { $crate::x64::ast::Mnemonic::Vmptrst };
    (vmread) => { $crate::x64::ast::Mnemonic::Vmread };
    (vmresume) => { $crate::x64::ast::Mnemonic::Vmresume };
    (vmwrite) => { $crate::x64::ast::Mnemonic::Vmwrite };
    (vmxoff) => { $crate::x64::ast::Mnemonic::Vmxoff };
    (vmxon) => { $crate::x64::ast::Mnemonic::Vmxon };
    (wait) => { $crate::x64::ast::Mnemonic::Wait };
    (wbinvd) => { $crate::x64::ast::Mnemonic::Wbinvd };
    (wrmsr) => { $crate::x64::ast::Mnemonic::Wrmsr };
    (xadd) => { $crate::x64::ast::Mnemonic::Xadd };
    (xchg) => { $crate::x64::ast::Mnemonic::Xchg };
    (xgetbv) => { $crate::x64::ast::Mnemonic::Xgetbv };
    (xlat) => { $crate::x64::ast::Mnemonic::Xlat };
    (xlatb) => { $crate::x64::ast::Mnemonic::Xlatb };
    (xor) => { $crate::x64::ast::Mnemonic::Xor };
    (xorpd) => { $crate::x64::ast::Mnemonic::Xorpd };
    (xorps) => { $crate::x64::ast::Mnemonic::Xorps };
    (xrstor) => { $crate::x64::ast::Mnemonic::Xrstor };
    (xsave) => { $crate::x64::ast::Mnemonic::Xsave };
    (xsetbv) => { $crate::x64::ast::Mnemonic::Xsetbv };
    ($m:tt) => { compile_error!(concat!("unknown x64 instruction mnemonic: ", stringify!($m))) };
}
pub use x64_mnemonic;


use crate::template::Template;

#[derive(Clone, Copy)]
pub enum Prefix { Es, Cs, Ntaken, Ss, Ds, Taken, Fs, Alter, Gs, Lock, Repnz, Repne, Rep, Repz, Repe }

impl Prefix {
    pub(crate) const fn encode(self) -> Template {
        use Prefix::*;
        match self {

            Es => Template::bytes(*b"\x26" ),
            Cs => Template::bytes(*b"\x2E" ),
            Ntaken => Template::bytes(*b"\x2E" ),
            Ss => Template::bytes(*b"\x36" ),
            Ds => Template::bytes(*b"\x3E" ),
            Taken => Template::bytes(*b"\x3E" ),
            Fs => Template::bytes(*b"\x64" ),
            Alter => Template::bytes(*b"\x64" ),
            Gs => Template::bytes(*b"\x65" ),
            Lock => Template::bytes(*b"\xF0" ),
            Repnz => Template::bytes(*b"\xF2" ),
            Repne => Template::bytes(*b"\xF2" ),
            Rep => Template::bytes(*b"\xF3" ),
            Repz => Template::bytes(*b"\xF3" ),
            Repe => Template::bytes(*b"\xF3" ),
        }
    }
}

#[macro_export]
macro_rules! x64_prefixes {
    ( $next:ident; $($tts:tt)* ) => {
        $crate::x64::ast::x64_prefixes!( @prefixes [$next] [] $($tts)* )
    };


     (@prefixes [$next: ident] [$($prefixes:ident),*] es $($rest:tt)*) => {
        $crate::x64::ast::x64_prefixes!(@prefixes [$next] [$($prefixes,)* Es] $($rest)*)
     };

     (@prefixes [$next: ident] [$($prefixes:ident),*] cs $($rest:tt)*) => {
        $crate::x64::ast::x64_prefixes!(@prefixes [$next] [$($prefixes,)* Cs] $($rest)*)
     };

     (@prefixes [$next: ident] [$($prefixes:ident),*] ntaken $($rest:tt)*) => {
        $crate::x64::ast::x64_prefixes!(@prefixes [$next] [$($prefixes,)* Ntaken] $($rest)*)
     };

     (@prefixes [$next: ident] [$($prefixes:ident),*] ss $($rest:tt)*) => {
        $crate::x64::ast::x64_prefixes!(@prefixes [$next] [$($prefixes,)* Ss] $($rest)*)
     };

     (@prefixes [$next: ident] [$($prefixes:ident),*] ds $($rest:tt)*) => {
        $crate::x64::ast::x64_prefixes!(@prefixes [$next] [$($prefixes,)* Ds] $($rest)*)
     };

     (@prefixes [$next: ident] [$($prefixes:ident),*] taken $($rest:tt)*) => {
        $crate::x64::ast::x64_prefixes!(@prefixes [$next] [$($prefixes,)* Taken] $($rest)*)
     };

     (@prefixes [$next: ident] [$($prefixes:ident),*] fs $($rest:tt)*) => {
        $crate::x64::ast::x64_prefixes!(@prefixes [$next] [$($prefixes,)* Fs] $($rest)*)
     };

     (@prefixes [$next: ident] [$($prefixes:ident),*] alter $($rest:tt)*) => {
        $crate::x64::ast::x64_prefixes!(@prefixes [$next] [$($prefixes,)* Alter] $($rest)*)
     };

     (@prefixes [$next: ident] [$($prefixes:ident),*] gs $($rest:tt)*) => {
        $crate::x64::ast::x64_prefixes!(@prefixes [$next] [$($prefixes,)* Gs] $($rest)*)
     };

     (@prefixes [$next: ident] [$($prefixes:ident),*] lock $($rest:tt)*) => {
        $crate::x64::ast::x64_prefixes!(@prefixes [$next] [$($prefixes,)* Lock] $($rest)*)
     };

     (@prefixes [$next: ident] [$($prefixes:ident),*] repnz $($rest:tt)*) => {
        $crate::x64::ast::x64_prefixes!(@prefixes [$next] [$($prefixes,)* Repnz] $($rest)*)
     };

     (@prefixes [$next: ident] [$($prefixes:ident),*] repne $($rest:tt)*) => {
        $crate::x64::ast::x64_prefixes!(@prefixes [$next] [$($prefixes,)* Repne] $($rest)*)
     };

     (@prefixes [$next: ident] [$($prefixes:ident),*] rep $($rest:tt)*) => {
        $crate::x64::ast::x64_prefixes!(@prefixes [$next] [$($prefixes,)* Rep] $($rest)*)
     };

     (@prefixes [$next: ident] [$($prefixes:ident),*] repz $($rest:tt)*) => {
        $crate::x64::ast::x64_prefixes!(@prefixes [$next] [$($prefixes,)* Repz] $($rest)*)
     };

     (@prefixes [$next: ident] [$($prefixes:ident),*] repe $($rest:tt)*) => {
        $crate::x64::ast::x64_prefixes!(@prefixes [$next] [$($prefixes,)* Repe] $($rest)*)
     };


    ( @prefixes [$next:ident] [$($prefixes:ident),*] $($rest:tt)*) => {
        $crate::x64::ast::$next!( [$($prefixes),*]; $($rest)* )
    };
}
pub use x64_prefixes;

impl crate::x64::ast::Instruction {
    pub const fn encoding(&self) -> crate::x64::Encoding {
        use crate::x64::ast::{Mnemonic as M, Operands as Os, Operand as O};
        use crate::x64::{Size as Sz, Encoding as Enc, EncodingRm as Erm};

        match (self.mnemonic, self.operands) {

            (M::Jmpe, Os::Z) => {
                Enc { op: b"\x0F\x00" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Vmcall, Os::Z) => {
                Enc { op: b"\x0F\x01\xC1" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Vmlaunch, Os::Z) => {
                Enc { op: b"\x0F\x01\xC2" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Vmresume, Os::Z) => {
                Enc { op: b"\x0F\x01\xC3" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Vmxoff, Os::Z) => {
                Enc { op: b"\x0F\x01\xC4" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Monitor, Os::Z) => {
                Enc { op: b"\x0F\x01\xC8" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Mwait, Os::Z) => {
                Enc { op: b"\x0F\x01\xC9" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Xgetbv, Os::Z) => {
                Enc { op: b"\x0F\x01\xD0" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Xsetbv, Os::Z) => {
                Enc { op: b"\x0F\x01\xD1" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Swapgs, Os::Z) => {
                Enc { op: b"\x0F\x01\xF8" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Rdtscp, Os::Z) => {
                Enc { op: b"\x0F\x01\xF9" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Loadall, Os::Z) => {
                Enc { op: b"\x0F\x05" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Syscall, Os::Z) => {
                Enc { op: b"\x0F\x05" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Clts, Os::Z) => {
                Enc { op: b"\x0F\x06" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Loadall, Os::Z) => {
                Enc { op: b"\x0F\x07" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Sysret, Os::Z) => {
                Enc { op: b"\x0F\x07" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Invd, Os::Z) => {
                Enc { op: b"\x0F\x08" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Wbinvd, Os::Z) => {
                Enc { op: b"\x0F\x09" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Ud2, Os::Z) => {
                Enc { op: b"\x0F\x0B" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Wrmsr, Os::Z) => {
                Enc { op: b"\x0F\x30" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Rdtsc, Os::Z) => {
                Enc { op: b"\x0F\x31" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Rdmsr, Os::Z) => {
                Enc { op: b"\x0F\x32" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Rdpmc, Os::Z) => {
                Enc { op: b"\x0F\x33" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Sysenter, Os::Z) => {
                Enc { op: b"\x0F\x34" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Sysenter, Os::Z) => {
                Enc { op: b"\x0F\x34" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Sysexit, Os::Z) => {
                Enc { op: b"\x0F\x35" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Getsec, Os::Z) => {
                Enc { op: b"\x0F\x37" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Emms, Os::Z) => {
                Enc { op: b"\x0F\x77" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Cpuid, Os::Z) => {
                Enc { op: b"\x0F\xA2" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Rsm, Os::Z) => {
                Enc { op: b"\x0F\xAA" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Lfence, Os::Z) => {
                Enc { op: b"\x0F\xAE" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Mfence, Os::Z) => {
                Enc { op: b"\x0F\xAE" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Sfence, Os::Z) => {
                Enc { op: b"\x0F\xAE" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Jmpe, Os::Z) => {
                Enc { op: b"\x0F\xB8" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Daa, Os::Z) => {
                Enc { op: b"\x27" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Das, Os::Z) => {
                Enc { op: b"\x2F" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Aaa, Os::Z) => {
                Enc { op: b"\x37" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Aas, Os::Z) => {
                Enc { op: b"\x3F" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Pusha, Os::Z) => {
                Enc { op: b"\x60" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Pushad, Os::Z) => {
                Enc { op: b"\x60" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Popa, Os::Z) => {
                Enc { op: b"\x61" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Popad, Os::Z) => {
                Enc { op: b"\x61" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Insb, Os::Z) => {
                Enc { op: b"\x6C" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Insw, Os::Z) => {
                Enc { op: b"\x6D" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Insd, Os::Z) => {
                Enc { op: b"\x6D" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Outsb, Os::Z) => {
                Enc { op: b"\x6E" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Outsw, Os::Z) => {
                Enc { op: b"\x6F" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Outsd, Os::Z) => {
                Enc { op: b"\x6F" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Nop, Os::Z) => {
                Enc { op: b"\x90" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Nop, Os::Z) => {
                Enc { op: b"\x90" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Pause, Os::Z) => {
                Enc { op: b"\x90" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Cbw, Os::Z) => {
                Enc { op: b"\x98" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Cbw, Os::Z) => {
                Enc { op: b"\x98" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Cwde, Os::Z) => {
                Enc { op: b"\x98" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Cwde, Os::Z) => {
                Enc { op: b"\x98" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Cdqe, Os::Z) => {
                Enc { op: b"\x98" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Cwd, Os::Z) => {
                Enc { op: b"\x99" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Cwd, Os::Z) => {
                Enc { op: b"\x99" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Cdq, Os::Z) => {
                Enc { op: b"\x99" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Cdq, Os::Z) => {
                Enc { op: b"\x99" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Cqo, Os::Z) => {
                Enc { op: b"\x99" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Fwait, Os::Z) => {
                Enc { op: b"\x9B" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Wait, Os::Z) => {
                Enc { op: b"\x9B" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Pushf, Os::Z) => {
                Enc { op: b"\x9C" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Pushf, Os::Z) => {
                Enc { op: b"\x9C" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Pushfd, Os::Z) => {
                Enc { op: b"\x9C" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Pushfq, Os::Z) => {
                Enc { op: b"\x9C" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Popf, Os::Z) => {
                Enc { op: b"\x9D" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Popf, Os::Z) => {
                Enc { op: b"\x9D" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Popfd, Os::Z) => {
                Enc { op: b"\x9D" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Popfq, Os::Z) => {
                Enc { op: b"\x9D" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Sahf, Os::Z) => {
                Enc { op: b"\x9E" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Lahf, Os::Z) => {
                Enc { op: b"\x9F" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Movsb, Os::Z) => {
                Enc { op: b"\xA4" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Movsw, Os::Z) => {
                Enc { op: b"\xA5" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Movsw, Os::Z) => {
                Enc { op: b"\xA5" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Movsd, Os::Z) => {
                Enc { op: b"\xA5" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Movsd, Os::Z) => {
                Enc { op: b"\xA5" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Movsq, Os::Z) => {
                Enc { op: b"\xA5" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Cmpsb, Os::Z) => {
                Enc { op: b"\xA6" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Cmpsw, Os::Z) => {
                Enc { op: b"\xA7" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Cmpsw, Os::Z) => {
                Enc { op: b"\xA7" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Cmpsd, Os::Z) => {
                Enc { op: b"\xA7" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Cmpsd, Os::Z) => {
                Enc { op: b"\xA7" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Cmpsq, Os::Z) => {
                Enc { op: b"\xA7" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Stosb, Os::Z) => {
                Enc { op: b"\xAA" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Stosw, Os::Z) => {
                Enc { op: b"\xAB" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Stosw, Os::Z) => {
                Enc { op: b"\xAB" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Stosd, Os::Z) => {
                Enc { op: b"\xAB" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Stosd, Os::Z) => {
                Enc { op: b"\xAB" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Stosq, Os::Z) => {
                Enc { op: b"\xAB" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Lodsb, Os::Z) => {
                Enc { op: b"\xAC" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Lodsw, Os::Z) => {
                Enc { op: b"\xAD" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Lodsw, Os::Z) => {
                Enc { op: b"\xAD" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Lodsd, Os::Z) => {
                Enc { op: b"\xAD" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Lodsd, Os::Z) => {
                Enc { op: b"\xAD" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Lodsq, Os::Z) => {
                Enc { op: b"\xAD" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Scasb, Os::Z) => {
                Enc { op: b"\xAE" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Scasw, Os::Z) => {
                Enc { op: b"\xAF" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Scasw, Os::Z) => {
                Enc { op: b"\xAF" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Scasd, Os::Z) => {
                Enc { op: b"\xAF" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Scasd, Os::Z) => {
                Enc { op: b"\xAF" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Scasq, Os::Z) => {
                Enc { op: b"\xAF" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Retn, Os::Z) => {
                Enc { op: b"\xC3" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Leave, Os::Z) => {
                Enc { op: b"\xC9" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Leave, Os::Z) => {
                Enc { op: b"\xC9" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Retf, Os::Z) => {
                Enc { op: b"\xCB" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Into, Os::Z) => {
                Enc { op: b"\xCE" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Iret, Os::Z) => {
                Enc { op: b"\xCF" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Iret, Os::Z) => {
                Enc { op: b"\xCF" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Iretd, Os::Z) => {
                Enc { op: b"\xCF" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Iretd, Os::Z) => {
                Enc { op: b"\xCF" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Iretq, Os::Z) => {
                Enc { op: b"\xCF" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Aam, Os::Z) => {
                Enc { op: b"\xD4\x0A" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Aad, Os::Z) => {
                Enc { op: b"\xD5\x0A" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Salc, Os::Z) => {
                Enc { op: b"\xD6" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Setalc, Os::Z) => {
                Enc { op: b"\xD6" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Xlatb, Os::Z) => {
                Enc { op: b"\xD7" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Fcom, Os::Z) => {
                Enc { op: b"\xD8\xD1" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Fcomp, Os::Z) => {
                Enc { op: b"\xD8\xD9" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Fxch, Os::Z) => {
                Enc { op: b"\xD9\xC9" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Fnop, Os::Z) => {
                Enc { op: b"\xD9\xD0" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Fchs, Os::Z) => {
                Enc { op: b"\xD9\xE0" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Fabs, Os::Z) => {
                Enc { op: b"\xD9\xE1" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Ftst, Os::Z) => {
                Enc { op: b"\xD9\xE4" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Fxam, Os::Z) => {
                Enc { op: b"\xD9\xE5" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Fld1, Os::Z) => {
                Enc { op: b"\xD9\xE8" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Fldl2t, Os::Z) => {
                Enc { op: b"\xD9\xE9" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Fldl2e, Os::Z) => {
                Enc { op: b"\xD9\xEA" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Fldpi, Os::Z) => {
                Enc { op: b"\xD9\xEB" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Fldlg2, Os::Z) => {
                Enc { op: b"\xD9\xEC" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Fldln2, Os::Z) => {
                Enc { op: b"\xD9\xED" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Fldz, Os::Z) => {
                Enc { op: b"\xD9\xEE" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::F2xm1, Os::Z) => {
                Enc { op: b"\xD9\xF0" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Fyl2x, Os::Z) => {
                Enc { op: b"\xD9\xF1" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Fptan, Os::Z) => {
                Enc { op: b"\xD9\xF2" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Fpatan, Os::Z) => {
                Enc { op: b"\xD9\xF3" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Fxtract, Os::Z) => {
                Enc { op: b"\xD9\xF4" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Fprem1, Os::Z) => {
                Enc { op: b"\xD9\xF5" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Fdecstp, Os::Z) => {
                Enc { op: b"\xD9\xF6" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Fincstp, Os::Z) => {
                Enc { op: b"\xD9\xF7" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Fprem, Os::Z) => {
                Enc { op: b"\xD9\xF8" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Fyl2xp1, Os::Z) => {
                Enc { op: b"\xD9\xF9" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Fsqrt, Os::Z) => {
                Enc { op: b"\xD9\xFA" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Fsincos, Os::Z) => {
                Enc { op: b"\xD9\xFB" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Frndint, Os::Z) => {
                Enc { op: b"\xD9\xFC" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Fscale, Os::Z) => {
                Enc { op: b"\xD9\xFD" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Fsin, Os::Z) => {
                Enc { op: b"\xD9\xFE" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Fcos, Os::Z) => {
                Enc { op: b"\xD9\xFF" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Fucompp, Os::Z) => {
                Enc { op: b"\xDA\xE9" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Fneni, Os::Z) => {
                Enc { op: b"\xDB\xE0" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Fneni, Os::Z) => {
                Enc { op: b"\xDB\xE0" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Feni, Os::Z) => {
                Enc { op: b"\xDB\xE0" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Fndisi, Os::Z) => {
                Enc { op: b"\xDB\xE1" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Fndisi, Os::Z) => {
                Enc { op: b"\xDB\xE1" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Fdisi, Os::Z) => {
                Enc { op: b"\xDB\xE1" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Fnclex, Os::Z) => {
                Enc { op: b"\xDB\xE2" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Fclex, Os::Z) => {
                Enc { op: b"\xDB\xE2" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Fninit, Os::Z) => {
                Enc { op: b"\xDB\xE3" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Finit, Os::Z) => {
                Enc { op: b"\xDB\xE3" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Fnsetpm, Os::Z) => {
                Enc { op: b"\xDB\xE4" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Fnsetpm, Os::Z) => {
                Enc { op: b"\xDB\xE4" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Fsetpm, Os::Z) => {
                Enc { op: b"\xDB\xE4" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Fucom, Os::Z) => {
                Enc { op: b"\xDD\xE1" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Fucomp, Os::Z) => {
                Enc { op: b"\xDD\xE9" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Faddp, Os::Z) => {
                Enc { op: b"\xDE\xC1" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Fmulp, Os::Z) => {
                Enc { op: b"\xDE\xC9" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Fcompp, Os::Z) => {
                Enc { op: b"\xDE\xD9" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Fsubrp, Os::Z) => {
                Enc { op: b"\xDE\xE1" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Fsubp, Os::Z) => {
                Enc { op: b"\xDE\xE9" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Fdivrp, Os::Z) => {
                Enc { op: b"\xDE\xF1" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Fdivp, Os::Z) => {
                Enc { op: b"\xDE\xF9" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Int1, Os::Z) => {
                Enc { op: b"\xF1" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Icebp, Os::Z) => {
                Enc { op: b"\xF1" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Hlt, Os::Z) => {
                Enc { op: b"\xF4" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Cmc, Os::Z) => {
                Enc { op: b"\xF5" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Clc, Os::Z) => {
                Enc { op: b"\xF8" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Stc, Os::Z) => {
                Enc { op: b"\xF9" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Cli, Os::Z) => {
                Enc { op: b"\xFA" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Sti, Os::Z) => {
                Enc { op: b"\xFB" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Cld, Os::Z) => {
                Enc { op: b"\xFC" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (M::Std, Os::Z) => {
                Enc { op: b"\xFD" , sz: Sz::None, rex_w: false, reg: None, rm: Erm::None, ext: None, tail: None, }
            },

            (_, _) => panic!("unsupported instruction type"),
        }
    }
}
